### ISSUE TITLE
The Observer can kill executions at the wrong time

### ISSUE THREAD

**Issue by dvenza** [DistributedSystemsGroup/zoe#22]
If the Spark application is restarted when the Observer is checking for the idle time, it will fail and use the time the execution started.
The Observer should keep the last known idle value for each execution and check if the new value is consistent (at most `loop_time`).

**Comment by fraPace** [comment]
The Observer is also killing a Jupyter Notebook powered by Spark in the following scenario:
1) The user is working on the notebook
2) The user decided to restart the kernel (and thus the Spark Application) but does not run any cell of the Notebook (and therefore the Spark application has 0 jobs)
3) The user goes away from keyboard a time greater than the interval that the Observer is using to check for idle time
4) The Observer detect that the currently running application has 0 jobs and consider the Zoe Application been idle since the its creation
5) The Observer kills the Zoe Application

I believe that both the previous and this issue can be solved by using, instead of the Zoe Application creation time, the last known non-idle time.

**Comment by dvenza** [comment]
Fixed in 0.10
